In [1]:
import numpy as np


In [2]:
mylist=[1,2,3,4,5,6,7,8]

In [7]:
arr=np.array(mylist)

In [4]:
mylist1=[[1,2,3,4],[5,6,7,8]]

In [5]:
mylist1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
mat=np.array(mylist1)

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
mat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.random.rand(10)

array([0.73482682, 0.61927795, 0.13290282, 0.44322565, 0.87606341,
       0.2795682 , 0.4351319 , 0.11688292, 0.60412532, 0.95671302])

In [16]:
np.random.randn(10)

array([-0.19047482,  0.97217949, -1.85062166, -1.3148748 ,  1.07867999,
       -1.20338031,  0.21886795, -1.15729993,  0.49257632, -0.52726407])

In [18]:
np.random.randint(1,100,10)

array([44,  8, 23, 51, 32, 16, 40, 37, 59, 68])

In [19]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [24]:
np.random.rand(2,3)

array([[0.35100078, 0.07500631, 0.37050748],
       [0.30533515, 0.88465614, 0.2398681 ]])

In [25]:
np.random.randn(2,3)

array([[ 0.51303052,  1.41371153, -0.26105342],
       [ 0.66450363,  1.42984101, -1.31428893]])

In [27]:
mat2=np.random.randint(1,100,25)


In [28]:
mat2

array([18, 80, 75, 18, 17, 25, 76, 95, 68, 42, 49, 52, 51, 23, 70, 97, 94,
       19, 81, 22, 20, 65, 25, 69, 59])

mat2.reshape(5,5)

In [29]:
mat2.reshape(5,5)

array([[18, 80, 75, 18, 17],
       [25, 76, 95, 68, 42],
       [49, 52, 51, 23, 70],
       [97, 94, 19, 81, 22],
       [20, 65, 25, 69, 59]])

In [30]:
mat2.dtype

dtype('int64')

In [32]:
mat2.shape

(25,)

In [33]:
mat3=np.arange(1,11)

In [34]:
mat3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
mat3[0]

1

In [38]:
mat3[5]

6

In [40]:
mat3[1:5]

array([2, 3, 4, 5])

In [41]:
mat4=np.random.randint(1,100,9).reshape(3,3)

In [42]:
mat4

array([[15, 98, 59],
       [19, 40, 19],
       [74, 30, 80]])

In [43]:
mat4[1][1]

40

In [44]:
mat4[1,1]

40

In [45]:
mat4[2,2]

80

mat4=[1,2]

In [46]:
mat4[1,2]

19

In [50]:
mat4[0:,:1]

array([[15],
       [19],
       [74]])

In [55]:
mat4[,0]

SyntaxError: invalid syntax (<ipython-input-55-9fb928b8bc7d>, line 1)

In [56]:
mat5=np.random.randint(1,100,20)

In [57]:
mat5

array([92, 77, 19, 94, 41, 76,  9, 30, 27, 32, 52, 13, 87, 58, 36, 94, 39,
       42, 10, 52])

In [58]:
mat5.sum()

980

In [59]:
mat5.mean()

49.0

In [62]:
mat5.min()

9

In [63]:
mat5.max()

94

In [66]:
mat5.std()

28.09626309671804

mat6=np.random.randint(1,100,9).rashape(3,3)
mat7=np.random.randint(1,100,9).rashape(3,3)

In [69]:
mat6=np.random.randint(1,100,9).reshape(3,3)
mat7=np.random.randint(1,100,9).reshape(3,3)

In [70]:
mat6

array([[54, 71, 96],
       [83, 22, 14],
       [58, 14, 19]])

In [71]:
mat7

array([[86, 21, 36],
       [58, 92, 15],
       [42, 52, 61]])

In [72]:
mat6+mat7

array([[140,  92, 132],
       [141, 114,  29],
       [100,  66,  80]])

In [73]:
mat6-mat7

array([[-32,  50,  60],
       [ 25, -70,  -1],
       [ 16, -38, -42]])

In [74]:
mat6/mat7

array([[0.62790698, 3.38095238, 2.66666667],
       [1.43103448, 0.23913043, 0.93333333],
       [1.38095238, 0.26923077, 0.31147541]])

In [75]:
mat6*mat7

array([[4644, 1491, 3456],
       [4814, 2024,  210],
       [2436,  728, 1159]])

In [76]:
mat6**mat7

array([[                   0, -8468284532194763417,                    0],
       [   86926657675520457,                    0,   155568095557812224],
       [-4875810701651738624,  2166231420765208576,  -109669468959689245]])

In [77]:
mat8=np.random.randint(1,100,10)

In [79]:
mat8-100

array([-11, -79,  -4, -20, -89, -29, -23,  -4, -77, -67])

In [80]:
mat8*10

array([890, 210, 960, 800, 110, 710, 770, 960, 230, 330])

In [81]:
mat8+5

array([ 94,  26, 101,  85,  16,  76,  82, 101,  28,  38])

In [83]:
mat8.sort()

In [84]:
mat8

array([11, 21, 23, 33, 71, 77, 80, 89, 96, 96])